### ISSUE TITLE
[Feature]: Tracker/Server set up

### ISSUE THREAD

**Issue by lennyvong** [PoCInnovation/BotNet-Hybrid#8]
### Description

Let's start to deal with our trackers on the network !

### Expected behaviour

To set up our trackers correctly we need first to to be able to comunicate with the main server : 
Main server view :
- [x] Define a way to save Tracker adresses but not their groups.
- [ ] Be able assign a bot to a group with a special condition (ex : geolocalisation).
- [x] Be able to **send** and **receive** data coming from trackers (for now).

Tracer view : 
- [ ] Be able to **receive** data from the server.
- [ ] Identify correctly that the data received coming from the server.

### Environment

- OS and version

### Proposed solution

/
