### ISSUE TITLE
[Feature]: Tracker/Bots set up

### ISSUE THREAD

**Issue by lennyvong** [PoCInnovation/BotNet-Hybrid#9]
### Description

Let's start to deal with the comunication between trackers and bots !

### Expected behaviour

For our network we need to be able to comunicate with our bots by our trackers.

To do that here the importants points from bot view: 
- [x] Be able to identify himself to one tracker after the comunication with the main server.
- [x] Find a way to identify a mssage which coming from his tracker and his tracker only (with a secret or something).
- [ ] Find a way to save his pairs adresses.
- [ ] Be able to pass data coming from thhe tracker to his pairs.

Tracker view :
- [ ] Save somewhere the list of the bots he can access.
- [ ] Be able to send and receive data coming from a bot.
- [ ] When we want to send a cmd, try find how can we select at which bot we'll send data first.

### Environment

- OS and version
